import { NativeTabs } from "expo-router/unstable-native-tabs";
import { color } from "@/theme/tokens";

// Native tab bar (real UITabBar on iOS / Material on Android). Warm-dark canon via the
// token adapter; Eclipse Gold is the selected accent (One Sun). Five top-level surfaces —
// the two ways to browse the findings (Feed / Archive), the set builder as the prominent
// CENTRE item (Mix), then the two operator-adopted audio surfaces (Radio / Mixtapes). Five
// short labels sit within the iOS 26 floating pill at 390px; the tint marks selection, so a
// symbol without a `.fill` twin still reads. Labels stay literal (the Chrome Rule).
// NativeTabs renders in a dev client / native build, not plain Expo Go.
//
// THE MIX CENTRE ITEM is the app's standalone tool (the web `/mix` "Chain a set"): an
// Instagram-style prominent centre tab — a full Eclipse Gold disc with a "merge into one"
// arrow knocked out (assets/mix-tab-icon.png, regenerated by scripts/gen-mix-tab-icon.sh).
// It renders `renderingMode="original"` (Expo SDK 55+; this app is SDK 56) so the disc stays
// gold whether the tab is selected or not, instead of being template-tinted grey when
// unselected — the one place a bitmap icon is right rather than an SF symbol. The other four
// stay SF symbols; the gold disc is deliberately the single exception, not a new pattern.
//
// IA is an OPERATOR-TASTE CHECKPOINT: five peer tabs, each mapping to a distinct web surface
// (/mix, radio.fluncle.com, /mixtapes); Mix takes the middle slot because it is the tool the
// app wants a stranger to find, and the centre is where the thumb lands.
export default function TabsLayout() {
  return (
    <NativeTabs
      backgroundColor={color.sleeveBlack}
      labelStyle={{ color: color.stardust }}
      tintColor={color.eclipseGold}
    >
      <NativeTabs.Trigger name="index">
        <NativeTabs.Trigger.Label>Feed</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="movie"
          sf={{ default: "play.rectangle", selected: "play.rectangle.fill" }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="archive">
        <NativeTabs.Trigger.Label>Archive</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="inventory_2"
          sf={{ default: "square.stack", selected: "square.stack.fill" }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="mix">
        <NativeTabs.Trigger.Label>Mix</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          renderingMode="original"
          src={require("../../assets/mix-tab-icon.png")}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="radio">
        <NativeTabs.Trigger.Label>Radio</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="radio"
          sf={{
            default: "dot.radiowaves.left.and.right",
            selected: "dot.radiowaves.left.and.right",
          }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="mixtapes">
        <NativeTabs.Trigger.Label>Mixtapes</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="queue_music"
          sf={{ default: "music.note.list", selected: "music.note.list" }}
        />
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
