import { NativeTabs } from "expo-router/unstable-native-tabs";
import { color } from "@/theme/tokens";

// Native tab bar (real UITabBar on iOS / Material on Android). Warm-dark canon via the
// token adapter; Eclipse Gold is the selected accent (One Sun). Five top-level surfaces —
// the two ways to browse the findings (Feed / Archive), the set builder as the prominent
// CENTRE item (Mix), then the two operator-adopted audio surfaces (Radio / Mixtapes). Five
// short labels sit within the iOS 26 floating pill at 390px; the tint marks selection, so a
// symbol without a `.fill` twin still reads. Labels stay literal (the Chrome Rule).
// NativeTabs renders in a dev client / native build, not plain Expo Go.
//
// THE DECKS CENTRE ITEM is the app's standalone tool (the web `/mix` "Chain a set"),
// labelled "Decks" — ratified Fluncle language (the live callout's "on the decks"), and
// where the tool puts you. ("Mix" collided with "Mixtapes" two slots over; "Set builder"
// read like chrome — operator-ruled 2026-07-13.) Its glyph is a custom Phosphor-grammar
// DJ rig (two platters + the mixer; assets/decks-tab-icon.png, regenerated by
// scripts/gen-decks-tab-icon.sh), template-tinted like its SF siblings. A permanently-gold
// disc was tried here (Instagram-style, `renderingMode="original"`) and RULED OUT: it
// fought the tab bar's own grammar (two golds, a circle inside the glass highlight). Every
// trigger obeys the bar's tint; the centre SLOT is the prominence.
//
// IA is an OPERATOR-TASTE CHECKPOINT: five peer tabs, each mapping to a distinct web surface
// (/mix, radio.fluncle.com, /mixtapes); Mix takes the middle slot because it is the tool the
// app wants a stranger to find, and the centre is where the thumb lands.
export default function TabsLayout() {
  return (
    <NativeTabs
      backgroundColor={color.sleeveBlack}
      labelStyle={{ color: color.stardust }}
      tintColor={color.eclipseGold}
    >
      <NativeTabs.Trigger name="index">
        <NativeTabs.Trigger.Label>Feed</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="movie"
          sf={{ default: "play.rectangle", selected: "play.rectangle.fill" }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="archive">
        <NativeTabs.Trigger.Label>Archive</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="inventory_2"
          sf={{ default: "square.stack", selected: "square.stack.fill" }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="mix">
        <NativeTabs.Trigger.Label>Decks</NativeTabs.Trigger.Label>
        {/* Both states name the same image: RNScreens requires icon and selectedIcon to be
            the SAME TYPE, and a bare src leaves selectedIcon in the sf family — the tint
            (stardust idle, gold selected) is the whole state change. */}
        <NativeTabs.Trigger.Icon
          renderingMode="template"
          src={{
            default: require("../../assets/decks-tab-icon.png"),
            selected: require("../../assets/decks-tab-icon.png"),
          }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="radio">
        <NativeTabs.Trigger.Label>Radio</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="radio"
          sf={{
            default: "dot.radiowaves.left.and.right",
            selected: "dot.radiowaves.left.and.right",
          }}
        />
      </NativeTabs.Trigger>
      <NativeTabs.Trigger name="mixtapes">
        <NativeTabs.Trigger.Label>Mixtapes</NativeTabs.Trigger.Label>
        <NativeTabs.Trigger.Icon
          md="queue_music"
          sf={{ default: "music.note.list", selected: "music.note.list" }}
        />
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
