#!/usr/bin/env bun

import { $ } from "bun";
import { createClient } from "@libsql/client/web";
import { REMOTE_DB_CONCURRENCY } from "../src/lib/database-concurrency";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { type DumpTable, type SchemaObject, type SqlValue } from "../src/lib/server/db-dump";

import { buildDumpSql, quoteIdent } from "../src/lib/server/db-dump";

const ITEM = process.env.FLUNCLE_TURSO_OP_ITEM;
if (!ITEM) {
  throw new Error(
    "Set FLUNCLE_TURSO_OP_ITEM to the 1Password item holding the production Turso credentials — see the ops runbook note.",
  );
}

async function readSecret(field: string): Promise<string> {
  try {
    const value = await $`op read ${`${ITEM}/${field}`}`.text();

    return value.trim();
  } catch {
    throw new Error(
      `Could not read ${field} from 1Password (${ITEM}). Unlock 1Password and enable its CLI integration, then retry.`,
    );
  }
}

const url = await readSecret("TURSO_DATABASE_URL");
const authToken = await readSecret("TURSO_AUTH_TOKEN");

const client = createClient({
  authToken,
  concurrency: REMOTE_DB_CONCURRENCY,
  intMode: "bigint",
  url,
});

const schemaResult = await client.execute(
  `SELECT type, name, sql FROM sqlite_master
   WHERE sql IS NOT NULL
     AND name NOT LIKE 'sqlite_%'
     AND name NOT LIKE 'libsql_%'
     AND name NOT LIKE '_litestream%'
     AND name NOT LIKE 'tracks_fts%'
   ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END, name`,
);

const schema: SchemaObject[] = schemaResult.rows.map((row) => ({
  name: row.name as string,
  sql: row.sql as string,
  type: row.type as string,
}));

const tables: DumpTable[] = [];

for (const object of schema) {
  if (object.type !== "table") {
    continue;
  }

  const result = await client.execute(`SELECT * FROM ${quoteIdent(object.name)}`);

  tables.push({
    columns: result.columns,
    name: object.name,
    rows: result.rows.map((row) =>
      result.columns.map((column) => (row as Record<string, unknown>)[column] as SqlValue),
    ),
  });
}

const sql = buildDumpSql(
  schema,
  tables,
  "-- Fluncle production snapshot. Generated by `bun run db:pull-prod`. Do not edit by hand.",
);

const outPath = join(".dev", "seed.sql");

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, sql, "utf8");

console.log(`Wrote ${outPath} (${tables.length} tables) from production.`);
