#!/usr/bin/env bun

import { $ } from "bun";
import { createClient } from "@libsql/client/web";
import { parseArgs } from "node:util";

import { REMOTE_DB_CONCURRENCY } from "../src/lib/database-concurrency";
import {
  devSnapshotPath,
  formatSnapshotReport,
  pullSnapshot,
  SNAPSHOT_PAGE_ROWS,
} from "./lib/db-snapshot";

async function readSecret(item: string, field: string): Promise<string> {
  try {
    const value = await $`op read ${`${item}/${field}`}`.text();

    return value.trim();
  } catch {
    throw new Error(
      `Could not read ${field} from 1Password (${item}). Unlock 1Password and enable its CLI integration, then retry.`,
    );
  }
}

function pageRowsFrom(raw: string | undefined): number {
  if (raw === undefined) {
    return SNAPSHOT_PAGE_ROWS;
  }

  const value = Number(raw);

  if (!Number.isInteger(value) || value < 1) {
    throw new Error(`--page-rows must be a positive integer, got "${raw}".`);
  }

  return value;
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: { "page-rows": { type: "string" } },
    strict: true,
  });
  const pageRows = pageRowsFrom(values["page-rows"]);
  const item = process.env.FLUNCLE_TURSO_OP_ITEM;

  if (!item) {
    throw new Error(
      "Set FLUNCLE_TURSO_OP_ITEM to the 1Password item holding the production Turso credentials — see the ops runbook note.",
    );
  }

  const url = await readSecret(item, "TURSO_DATABASE_URL");
  const authToken = await readSecret(item, "TURSO_AUTH_TOKEN");
  const client = createClient({
    authToken,
    concurrency: REMOTE_DB_CONCURRENCY,
    intMode: "bigint",
    url,
  });

  try {
    const outPath = devSnapshotPath();

    console.log(`Pulling production into ${outPath}, ${pageRows} rows per request…`);

    const report = await pullSnapshot({
      client,
      header:
        "-- Fluncle production snapshot. Generated by `bun run db:pull-prod`. Do not edit by hand.",
      log: (line) => console.log(line),
      outPath,
      pageRows,
    });

    console.log(formatSnapshotReport(report));
  } finally {
    client.close();
  }
}

try {
  await main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
