#!/usr/bin/env bun
/**
 * Dump the PRODUCTION Turso database into the golden local snapshot at
 * apps/web/.dev/seed.sql — the seed that worktrees clone (see db-refresh.ts).
 * Run it (normally in the main checkout) when you want local dev to catch up to
 * production.
 *
 * Production credentials are never stored in .dev.vars. They are read at run
 * time from 1Password — point `FLUNCLE_TURSO_OP_ITEM` at the item that holds the
 * production Turso credentials (see the ops runbook note) — so this is a
 * deliberate, human-in-the-loop step: `op` must be unlocked. The dump itself is
 * read-only (SELECTs).
 *
 * The SQL emitter is shared with the restore drill + the on-box backup sweep
 * (src/lib/server/db-dump.ts), so the dev seed and the R2 backups are the exact
 * same, continuously-restore-tested format.
 */
import { $ } from "bun";
import { createClient } from "@libsql/client/web";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { type DumpTable, type SchemaObject, type SqlValue } from "../src/lib/server/db-dump";

import { buildDumpSql, quoteIdent } from "../src/lib/server/db-dump";

const ITEM = process.env.FLUNCLE_TURSO_OP_ITEM;
if (!ITEM) {
  throw new Error(
    "Set FLUNCLE_TURSO_OP_ITEM to the 1Password item holding the production Turso credentials — see the ops runbook note.",
  );
}

async function readSecret(field: string): Promise<string> {
  try {
    const value = await $`op read ${`${ITEM}/${field}`}`.text();

    return value.trim();
  } catch {
    throw new Error(
      `Could not read ${field} from 1Password (${ITEM}). Unlock 1Password and enable its CLI integration, then retry.`,
    );
  }
}

const url = await readSecret("TURSO_DATABASE_URL");
const authToken = await readSecret("TURSO_AUTH_TOKEN");

// intMode:"bigint" keeps large integers exact through the dump (the shared emitter
// serialises a bigint by its precise decimal string).
const client = createClient({ authToken, intMode: "bigint", url });

const schemaResult = await client.execute(
  `SELECT type, name, sql FROM sqlite_master
   WHERE sql IS NOT NULL
     AND name NOT LIKE 'sqlite_%'
     AND name NOT LIKE 'libsql_%'
     AND name NOT LIKE '_litestream%'
   ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END, name`,
);

const schema: SchemaObject[] = schemaResult.rows.map((row) => ({
  name: row.name as string,
  sql: row.sql as string,
  type: row.type as string,
}));

const tables: DumpTable[] = [];

for (const object of schema) {
  if (object.type !== "table") {
    continue;
  }

  const result = await client.execute(`SELECT * FROM ${quoteIdent(object.name)}`);

  tables.push({
    columns: result.columns,
    name: object.name,
    rows: result.rows.map((row) =>
      result.columns.map((column) => (row as Record<string, unknown>)[column] as SqlValue),
    ),
  });
}

const sql = buildDumpSql(
  schema,
  tables,
  "-- Fluncle production snapshot. Generated by `bun run db:pull-prod`. Do not edit by hand.",
);

const outPath = join(".dev", "seed.sql");

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, sql, "utf8");

console.log(`Wrote ${outPath} (${tables.length} tables) from production.`);
