/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesLogIdRouteImport } from './routes/stories.$logId'
import { Route as CliLatestDotshRouteImport } from './routes/cli/latest[.]sh'
import { Route as ApiTracksRouteImport } from './routes/api/tracks'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiStoriesRouteImport } from './routes/api/stories'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTracksRandomRouteImport } from './routes/api/tracks/random'
import { Route as ApiTracksIdOrLogIdRouteImport } from './routes/api/tracks.$idOrLogId'
import { Route as ApiPreviewIdOrLogIdRouteImport } from './routes/api/preview.$idOrLogId'
import { Route as ApiAdminTracksRouteImport } from './routes/api/admin/tracks'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminTracksTrackIdRouteImport } from './routes/api/admin/tracks.$trackId'
import { Route as ApiAdminSubmissionsSubmissionIdRouteImport } from './routes/api/admin/submissions/$submissionId'
import { Route as ApiAdminTracksTrackIdVideoRouteImport } from './routes/api/admin/tracks.$trackId.video'
import { Route as ApiAdminTracksTrackIdSocialRouteImport } from './routes/api/admin/tracks.$trackId.social'
import { Route as ApiAdminSubmissionsSubmissionIdRejectRouteImport } from './routes/api/admin/submissions/$submissionId/reject'
import { Route as ApiAdminSubmissionsSubmissionIdApproveRouteImport } from './routes/api/admin/submissions/$submissionId/approve'
import { Route as ApiAdminSpotifyAuthStartRouteImport } from './routes/api/admin/spotify/auth/start'
import { Route as ApiAdminSpotifyAuthCallbackRouteImport } from './routes/api/admin/spotify/auth/callback'
import { Route as ApiAdminTracksTrackIdSocialPlatformRouteImport } from './routes/api/admin/tracks.$trackId.social.$platform'
import { Route as ApiAdminTracksTrackIdSocialPlatformDraftRouteImport } from './routes/api/admin/tracks.$trackId.social.$platform.draft'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesLogIdRoute = StoriesLogIdRouteImport.update({
  id: '/stories/$logId',
  path: '/stories/$logId',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLatestDotshRoute = CliLatestDotshRouteImport.update({
  id: '/cli/latest.sh',
  path: '/cli/latest.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracksRoute = ApiTracksRouteImport.update({
  id: '/api/tracks',
  path: '/api/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesRoute = ApiStoriesRouteImport.update({
  id: '/api/stories',
  path: '/api/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTracksRandomRoute = ApiTracksRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => ApiTracksRoute,
} as any)
const ApiTracksIdOrLogIdRoute = ApiTracksIdOrLogIdRouteImport.update({
  id: '/$idOrLogId',
  path: '/$idOrLogId',
  getParentRoute: () => ApiTracksRoute,
} as any)
const ApiPreviewIdOrLogIdRoute = ApiPreviewIdOrLogIdRouteImport.update({
  id: '/api/preview/$idOrLogId',
  path: '/api/preview/$idOrLogId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTracksRoute = ApiAdminTracksRouteImport.update({
  id: '/api/admin/tracks',
  path: '/api/admin/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTracksTrackIdRoute = ApiAdminTracksTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => ApiAdminTracksRoute,
} as any)
const ApiAdminSubmissionsSubmissionIdRoute =
  ApiAdminSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiAdminSubmissionsRoute,
  } as any)
const ApiAdminTracksTrackIdVideoRoute =
  ApiAdminTracksTrackIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => ApiAdminTracksTrackIdRoute,
  } as any)
const ApiAdminTracksTrackIdSocialRoute =
  ApiAdminTracksTrackIdSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => ApiAdminTracksTrackIdRoute,
  } as any)
const ApiAdminSubmissionsSubmissionIdRejectRoute =
  ApiAdminSubmissionsSubmissionIdRejectRouteImport.update({
    id: '/reject',
    path: '/reject',
    getParentRoute: () => ApiAdminSubmissionsSubmissionIdRoute,
  } as any)
const ApiAdminSubmissionsSubmissionIdApproveRoute =
  ApiAdminSubmissionsSubmissionIdApproveRouteImport.update({
    id: '/approve',
    path: '/approve',
    getParentRoute: () => ApiAdminSubmissionsSubmissionIdRoute,
  } as any)
const ApiAdminSpotifyAuthStartRoute =
  ApiAdminSpotifyAuthStartRouteImport.update({
    id: '/api/admin/spotify/auth/start',
    path: '/api/admin/spotify/auth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSpotifyAuthCallbackRoute =
  ApiAdminSpotifyAuthCallbackRouteImport.update({
    id: '/api/admin/spotify/auth/callback',
    path: '/api/admin/spotify/auth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTracksTrackIdSocialPlatformRoute =
  ApiAdminTracksTrackIdSocialPlatformRouteImport.update({
    id: '/$platform',
    path: '/$platform',
    getParentRoute: () => ApiAdminTracksTrackIdSocialRoute,
  } as any)
const ApiAdminTracksTrackIdSocialPlatformDraftRoute =
  ApiAdminTracksTrackIdSocialPlatformDraftRouteImport.update({
    id: '/draft',
    path: '/draft',
    getParentRoute: () => ApiAdminTracksTrackIdSocialPlatformRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stories': typeof ApiStoriesRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/tracks': typeof ApiTracksRouteWithChildren
  '/cli/latest.sh': typeof CliLatestDotshRoute
  '/stories/$logId': typeof StoriesLogIdRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tracks': typeof ApiAdminTracksRouteWithChildren
  '/api/preview/$idOrLogId': typeof ApiPreviewIdOrLogIdRoute
  '/api/tracks/$idOrLogId': typeof ApiTracksIdOrLogIdRoute
  '/api/tracks/random': typeof ApiTracksRandomRoute
  '/api/admin/submissions/$submissionId': typeof ApiAdminSubmissionsSubmissionIdRouteWithChildren
  '/api/admin/tracks/$trackId': typeof ApiAdminTracksTrackIdRouteWithChildren
  '/api/admin/spotify/auth/callback': typeof ApiAdminSpotifyAuthCallbackRoute
  '/api/admin/spotify/auth/start': typeof ApiAdminSpotifyAuthStartRoute
  '/api/admin/submissions/$submissionId/approve': typeof ApiAdminSubmissionsSubmissionIdApproveRoute
  '/api/admin/submissions/$submissionId/reject': typeof ApiAdminSubmissionsSubmissionIdRejectRoute
  '/api/admin/tracks/$trackId/social': typeof ApiAdminTracksTrackIdSocialRouteWithChildren
  '/api/admin/tracks/$trackId/video': typeof ApiAdminTracksTrackIdVideoRoute
  '/api/admin/tracks/$trackId/social/$platform': typeof ApiAdminTracksTrackIdSocialPlatformRouteWithChildren
  '/api/admin/tracks/$trackId/social/$platform/draft': typeof ApiAdminTracksTrackIdSocialPlatformDraftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stories': typeof ApiStoriesRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/tracks': typeof ApiTracksRouteWithChildren
  '/cli/latest.sh': typeof CliLatestDotshRoute
  '/stories/$logId': typeof StoriesLogIdRoute
  '/stories': typeof StoriesIndexRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tracks': typeof ApiAdminTracksRouteWithChildren
  '/api/preview/$idOrLogId': typeof ApiPreviewIdOrLogIdRoute
  '/api/tracks/$idOrLogId': typeof ApiTracksIdOrLogIdRoute
  '/api/tracks/random': typeof ApiTracksRandomRoute
  '/api/admin/submissions/$submissionId': typeof ApiAdminSubmissionsSubmissionIdRouteWithChildren
  '/api/admin/tracks/$trackId': typeof ApiAdminTracksTrackIdRouteWithChildren
  '/api/admin/spotify/auth/callback': typeof ApiAdminSpotifyAuthCallbackRoute
  '/api/admin/spotify/auth/start': typeof ApiAdminSpotifyAuthStartRoute
  '/api/admin/submissions/$submissionId/approve': typeof ApiAdminSubmissionsSubmissionIdApproveRoute
  '/api/admin/submissions/$submissionId/reject': typeof ApiAdminSubmissionsSubmissionIdRejectRoute
  '/api/admin/tracks/$trackId/social': typeof ApiAdminTracksTrackIdSocialRouteWithChildren
  '/api/admin/tracks/$trackId/video': typeof ApiAdminTracksTrackIdVideoRoute
  '/api/admin/tracks/$trackId/social/$platform': typeof ApiAdminTracksTrackIdSocialPlatformRouteWithChildren
  '/api/admin/tracks/$trackId/social/$platform/draft': typeof ApiAdminTracksTrackIdSocialPlatformDraftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stories': typeof ApiStoriesRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/tracks': typeof ApiTracksRouteWithChildren
  '/cli/latest.sh': typeof CliLatestDotshRoute
  '/stories/$logId': typeof StoriesLogIdRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/tracks': typeof ApiAdminTracksRouteWithChildren
  '/api/preview/$idOrLogId': typeof ApiPreviewIdOrLogIdRoute
  '/api/tracks/$idOrLogId': typeof ApiTracksIdOrLogIdRoute
  '/api/tracks/random': typeof ApiTracksRandomRoute
  '/api/admin/submissions/$submissionId': typeof ApiAdminSubmissionsSubmissionIdRouteWithChildren
  '/api/admin/tracks/$trackId': typeof ApiAdminTracksTrackIdRouteWithChildren
  '/api/admin/spotify/auth/callback': typeof ApiAdminSpotifyAuthCallbackRoute
  '/api/admin/spotify/auth/start': typeof ApiAdminSpotifyAuthStartRoute
  '/api/admin/submissions/$submissionId/approve': typeof ApiAdminSubmissionsSubmissionIdApproveRoute
  '/api/admin/submissions/$submissionId/reject': typeof ApiAdminSubmissionsSubmissionIdRejectRoute
  '/api/admin/tracks/$trackId/social': typeof ApiAdminTracksTrackIdSocialRouteWithChildren
  '/api/admin/tracks/$trackId/video': typeof ApiAdminTracksTrackIdVideoRoute
  '/api/admin/tracks/$trackId/social/$platform': typeof ApiAdminTracksTrackIdSocialPlatformRouteWithChildren
  '/api/admin/tracks/$trackId/social/$platform/draft': typeof ApiAdminTracksTrackIdSocialPlatformDraftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galaxy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/newsletter'
    | '/api/search'
    | '/api/stories'
    | '/api/submissions'
    | '/api/tracks'
    | '/cli/latest.sh'
    | '/stories/$logId'
    | '/stories/'
    | '/api/admin/submissions'
    | '/api/admin/tracks'
    | '/api/preview/$idOrLogId'
    | '/api/tracks/$idOrLogId'
    | '/api/tracks/random'
    | '/api/admin/submissions/$submissionId'
    | '/api/admin/tracks/$trackId'
    | '/api/admin/spotify/auth/callback'
    | '/api/admin/spotify/auth/start'
    | '/api/admin/submissions/$submissionId/approve'
    | '/api/admin/submissions/$submissionId/reject'
    | '/api/admin/tracks/$trackId/social'
    | '/api/admin/tracks/$trackId/video'
    | '/api/admin/tracks/$trackId/social/$platform'
    | '/api/admin/tracks/$trackId/social/$platform/draft'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galaxy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/newsletter'
    | '/api/search'
    | '/api/stories'
    | '/api/submissions'
    | '/api/tracks'
    | '/cli/latest.sh'
    | '/stories/$logId'
    | '/stories'
    | '/api/admin/submissions'
    | '/api/admin/tracks'
    | '/api/preview/$idOrLogId'
    | '/api/tracks/$idOrLogId'
    | '/api/tracks/random'
    | '/api/admin/submissions/$submissionId'
    | '/api/admin/tracks/$trackId'
    | '/api/admin/spotify/auth/callback'
    | '/api/admin/spotify/auth/start'
    | '/api/admin/submissions/$submissionId/approve'
    | '/api/admin/submissions/$submissionId/reject'
    | '/api/admin/tracks/$trackId/social'
    | '/api/admin/tracks/$trackId/video'
    | '/api/admin/tracks/$trackId/social/$platform'
    | '/api/admin/tracks/$trackId/social/$platform/draft'
  id:
    | '__root__'
    | '/'
    | '/galaxy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/newsletter'
    | '/api/search'
    | '/api/stories'
    | '/api/submissions'
    | '/api/tracks'
    | '/cli/latest.sh'
    | '/stories/$logId'
    | '/stories/'
    | '/api/admin/submissions'
    | '/api/admin/tracks'
    | '/api/preview/$idOrLogId'
    | '/api/tracks/$idOrLogId'
    | '/api/tracks/random'
    | '/api/admin/submissions/$submissionId'
    | '/api/admin/tracks/$trackId'
    | '/api/admin/spotify/auth/callback'
    | '/api/admin/spotify/auth/start'
    | '/api/admin/submissions/$submissionId/approve'
    | '/api/admin/submissions/$submissionId/reject'
    | '/api/admin/tracks/$trackId/social'
    | '/api/admin/tracks/$trackId/video'
    | '/api/admin/tracks/$trackId/social/$platform'
    | '/api/admin/tracks/$trackId/social/$platform/draft'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalaxyRoute: typeof GalaxyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStoriesRoute: typeof ApiStoriesRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  ApiTracksRoute: typeof ApiTracksRouteWithChildren
  CliLatestDotshRoute: typeof CliLatestDotshRoute
  StoriesLogIdRoute: typeof StoriesLogIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRouteWithChildren
  ApiAdminTracksRoute: typeof ApiAdminTracksRouteWithChildren
  ApiPreviewIdOrLogIdRoute: typeof ApiPreviewIdOrLogIdRoute
  ApiAdminSpotifyAuthCallbackRoute: typeof ApiAdminSpotifyAuthCallbackRoute
  ApiAdminSpotifyAuthStartRoute: typeof ApiAdminSpotifyAuthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$logId': {
      id: '/stories/$logId'
      path: '/stories/$logId'
      fullPath: '/stories/$logId'
      preLoaderRoute: typeof StoriesLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/latest.sh': {
      id: '/cli/latest.sh'
      path: '/cli/latest.sh'
      fullPath: '/cli/latest.sh'
      preLoaderRoute: typeof CliLatestDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracks': {
      id: '/api/tracks'
      path: '/api/tracks'
      fullPath: '/api/tracks'
      preLoaderRoute: typeof ApiTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories': {
      id: '/api/stories'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracks/random': {
      id: '/api/tracks/random'
      path: '/random'
      fullPath: '/api/tracks/random'
      preLoaderRoute: typeof ApiTracksRandomRouteImport
      parentRoute: typeof ApiTracksRoute
    }
    '/api/tracks/$idOrLogId': {
      id: '/api/tracks/$idOrLogId'
      path: '/$idOrLogId'
      fullPath: '/api/tracks/$idOrLogId'
      preLoaderRoute: typeof ApiTracksIdOrLogIdRouteImport
      parentRoute: typeof ApiTracksRoute
    }
    '/api/preview/$idOrLogId': {
      id: '/api/preview/$idOrLogId'
      path: '/api/preview/$idOrLogId'
      fullPath: '/api/preview/$idOrLogId'
      preLoaderRoute: typeof ApiPreviewIdOrLogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tracks': {
      id: '/api/admin/tracks'
      path: '/api/admin/tracks'
      fullPath: '/api/admin/tracks'
      preLoaderRoute: typeof ApiAdminTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tracks/$trackId': {
      id: '/api/admin/tracks/$trackId'
      path: '/$trackId'
      fullPath: '/api/admin/tracks/$trackId'
      preLoaderRoute: typeof ApiAdminTracksTrackIdRouteImport
      parentRoute: typeof ApiAdminTracksRoute
    }
    '/api/admin/submissions/$submissionId': {
      id: '/api/admin/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/admin/submissions/$submissionId'
      preLoaderRoute: typeof ApiAdminSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiAdminSubmissionsRoute
    }
    '/api/admin/tracks/$trackId/video': {
      id: '/api/admin/tracks/$trackId/video'
      path: '/video'
      fullPath: '/api/admin/tracks/$trackId/video'
      preLoaderRoute: typeof ApiAdminTracksTrackIdVideoRouteImport
      parentRoute: typeof ApiAdminTracksTrackIdRoute
    }
    '/api/admin/tracks/$trackId/social': {
      id: '/api/admin/tracks/$trackId/social'
      path: '/social'
      fullPath: '/api/admin/tracks/$trackId/social'
      preLoaderRoute: typeof ApiAdminTracksTrackIdSocialRouteImport
      parentRoute: typeof ApiAdminTracksTrackIdRoute
    }
    '/api/admin/submissions/$submissionId/reject': {
      id: '/api/admin/submissions/$submissionId/reject'
      path: '/reject'
      fullPath: '/api/admin/submissions/$submissionId/reject'
      preLoaderRoute: typeof ApiAdminSubmissionsSubmissionIdRejectRouteImport
      parentRoute: typeof ApiAdminSubmissionsSubmissionIdRoute
    }
    '/api/admin/submissions/$submissionId/approve': {
      id: '/api/admin/submissions/$submissionId/approve'
      path: '/approve'
      fullPath: '/api/admin/submissions/$submissionId/approve'
      preLoaderRoute: typeof ApiAdminSubmissionsSubmissionIdApproveRouteImport
      parentRoute: typeof ApiAdminSubmissionsSubmissionIdRoute
    }
    '/api/admin/spotify/auth/start': {
      id: '/api/admin/spotify/auth/start'
      path: '/api/admin/spotify/auth/start'
      fullPath: '/api/admin/spotify/auth/start'
      preLoaderRoute: typeof ApiAdminSpotifyAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/spotify/auth/callback': {
      id: '/api/admin/spotify/auth/callback'
      path: '/api/admin/spotify/auth/callback'
      fullPath: '/api/admin/spotify/auth/callback'
      preLoaderRoute: typeof ApiAdminSpotifyAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tracks/$trackId/social/$platform': {
      id: '/api/admin/tracks/$trackId/social/$platform'
      path: '/$platform'
      fullPath: '/api/admin/tracks/$trackId/social/$platform'
      preLoaderRoute: typeof ApiAdminTracksTrackIdSocialPlatformRouteImport
      parentRoute: typeof ApiAdminTracksTrackIdSocialRoute
    }
    '/api/admin/tracks/$trackId/social/$platform/draft': {
      id: '/api/admin/tracks/$trackId/social/$platform/draft'
      path: '/draft'
      fullPath: '/api/admin/tracks/$trackId/social/$platform/draft'
      preLoaderRoute: typeof ApiAdminTracksTrackIdSocialPlatformDraftRouteImport
      parentRoute: typeof ApiAdminTracksTrackIdSocialPlatformRoute
    }
  }
}

interface ApiTracksRouteChildren {
  ApiTracksIdOrLogIdRoute: typeof ApiTracksIdOrLogIdRoute
  ApiTracksRandomRoute: typeof ApiTracksRandomRoute
}

const ApiTracksRouteChildren: ApiTracksRouteChildren = {
  ApiTracksIdOrLogIdRoute: ApiTracksIdOrLogIdRoute,
  ApiTracksRandomRoute: ApiTracksRandomRoute,
}

const ApiTracksRouteWithChildren = ApiTracksRoute._addFileChildren(
  ApiTracksRouteChildren,
)

interface ApiAdminSubmissionsSubmissionIdRouteChildren {
  ApiAdminSubmissionsSubmissionIdApproveRoute: typeof ApiAdminSubmissionsSubmissionIdApproveRoute
  ApiAdminSubmissionsSubmissionIdRejectRoute: typeof ApiAdminSubmissionsSubmissionIdRejectRoute
}

const ApiAdminSubmissionsSubmissionIdRouteChildren: ApiAdminSubmissionsSubmissionIdRouteChildren =
  {
    ApiAdminSubmissionsSubmissionIdApproveRoute:
      ApiAdminSubmissionsSubmissionIdApproveRoute,
    ApiAdminSubmissionsSubmissionIdRejectRoute:
      ApiAdminSubmissionsSubmissionIdRejectRoute,
  }

const ApiAdminSubmissionsSubmissionIdRouteWithChildren =
  ApiAdminSubmissionsSubmissionIdRoute._addFileChildren(
    ApiAdminSubmissionsSubmissionIdRouteChildren,
  )

interface ApiAdminSubmissionsRouteChildren {
  ApiAdminSubmissionsSubmissionIdRoute: typeof ApiAdminSubmissionsSubmissionIdRouteWithChildren
}

const ApiAdminSubmissionsRouteChildren: ApiAdminSubmissionsRouteChildren = {
  ApiAdminSubmissionsSubmissionIdRoute:
    ApiAdminSubmissionsSubmissionIdRouteWithChildren,
}

const ApiAdminSubmissionsRouteWithChildren =
  ApiAdminSubmissionsRoute._addFileChildren(ApiAdminSubmissionsRouteChildren)

interface ApiAdminTracksTrackIdSocialPlatformRouteChildren {
  ApiAdminTracksTrackIdSocialPlatformDraftRoute: typeof ApiAdminTracksTrackIdSocialPlatformDraftRoute
}

const ApiAdminTracksTrackIdSocialPlatformRouteChildren: ApiAdminTracksTrackIdSocialPlatformRouteChildren =
  {
    ApiAdminTracksTrackIdSocialPlatformDraftRoute:
      ApiAdminTracksTrackIdSocialPlatformDraftRoute,
  }

const ApiAdminTracksTrackIdSocialPlatformRouteWithChildren =
  ApiAdminTracksTrackIdSocialPlatformRoute._addFileChildren(
    ApiAdminTracksTrackIdSocialPlatformRouteChildren,
  )

interface ApiAdminTracksTrackIdSocialRouteChildren {
  ApiAdminTracksTrackIdSocialPlatformRoute: typeof ApiAdminTracksTrackIdSocialPlatformRouteWithChildren
}

const ApiAdminTracksTrackIdSocialRouteChildren: ApiAdminTracksTrackIdSocialRouteChildren =
  {
    ApiAdminTracksTrackIdSocialPlatformRoute:
      ApiAdminTracksTrackIdSocialPlatformRouteWithChildren,
  }

const ApiAdminTracksTrackIdSocialRouteWithChildren =
  ApiAdminTracksTrackIdSocialRoute._addFileChildren(
    ApiAdminTracksTrackIdSocialRouteChildren,
  )

interface ApiAdminTracksTrackIdRouteChildren {
  ApiAdminTracksTrackIdSocialRoute: typeof ApiAdminTracksTrackIdSocialRouteWithChildren
  ApiAdminTracksTrackIdVideoRoute: typeof ApiAdminTracksTrackIdVideoRoute
}

const ApiAdminTracksTrackIdRouteChildren: ApiAdminTracksTrackIdRouteChildren = {
  ApiAdminTracksTrackIdSocialRoute:
    ApiAdminTracksTrackIdSocialRouteWithChildren,
  ApiAdminTracksTrackIdVideoRoute: ApiAdminTracksTrackIdVideoRoute,
}

const ApiAdminTracksTrackIdRouteWithChildren =
  ApiAdminTracksTrackIdRoute._addFileChildren(
    ApiAdminTracksTrackIdRouteChildren,
  )

interface ApiAdminTracksRouteChildren {
  ApiAdminTracksTrackIdRoute: typeof ApiAdminTracksTrackIdRouteWithChildren
}

const ApiAdminTracksRouteChildren: ApiAdminTracksRouteChildren = {
  ApiAdminTracksTrackIdRoute: ApiAdminTracksTrackIdRouteWithChildren,
}

const ApiAdminTracksRouteWithChildren = ApiAdminTracksRoute._addFileChildren(
  ApiAdminTracksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalaxyRoute: GalaxyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStoriesRoute: ApiStoriesRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  ApiTracksRoute: ApiTracksRouteWithChildren,
  CliLatestDotshRoute: CliLatestDotshRoute,
  StoriesLogIdRoute: StoriesLogIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRouteWithChildren,
  ApiAdminTracksRoute: ApiAdminTracksRouteWithChildren,
  ApiPreviewIdOrLogIdRoute: ApiPreviewIdOrLogIdRoute,
  ApiAdminSpotifyAuthCallbackRoute: ApiAdminSpotifyAuthCallbackRoute,
  ApiAdminSpotifyAuthStartRoute: ApiAdminSpotifyAuthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
