export const BANNED_WORDS = [
  "signal",
  "signals",
  "transmission",
  "transmissions",
  "anomaly",
  "curate",
  "curated",
  "curates",
  "curating",
  "curation",
  "curator",
  "curators",
  "content",
  "streaming",
] as const;
