import { describe, expect, test } from "bun:test";

import { colors, radii } from "../src/index";
import { renderTokensCss, TOKENS_CSS_URL } from "./generate-css";

describe("src/tokens.css is not stale", () => {
  test("matches a fresh render of the tokens, byte for byte", async () => {
    const committed = await Bun.file(TOKENS_CSS_URL).text();

    expect(committed).toBe(renderTokensCss());
  });

  test("carries every colour and radius token (the render covers both maps)", () => {
    const css = renderTokensCss();

    for (const name of Object.keys(colors)) {
      const variable = `--${name.replaceAll(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}:`;

      expect(css).toContain(variable);
    }

    for (const name of Object.keys(radii)) {
      expect(css).toContain(`--rounded-${name}:`);
    }
  });

  test("keeps the do-not-edit banner, so the file is never hand-maintained", () => {
    expect(renderTokensCss().startsWith("/* GENERATED by scripts/generate-css.ts")).toBe(true);
  });
});
