import { colors, radii } from "../src/index";

const toKebab = (value: string): string => value.replaceAll(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

export const TOKENS_CSS_URL = new URL("../src/tokens.css", import.meta.url);

export function renderTokensCss(): string {
  const lines: string[] = [
    "/* GENERATED by scripts/generate-css.ts from src/index.ts — do not edit by hand.",
    "   DESIGN.md is canonical; fix src/index.ts and re-run `bun run generate`. */",
    "",
    ":root {",
    ...Object.entries(colors).map(([name, value]) => `  --${toKebab(name)}: ${value};`),
    ...Object.entries(radii).map(([name, value]) => `  --rounded-${toKebab(name)}: ${value};`),
    "}",
    "",
  ];

  return lines.join("\n");
}

if (import.meta.main) {
  await Bun.write(TOKENS_CSS_URL, renderTokensCss());
  console.log("wrote src/tokens.css");
}
