// Emits src/tokens.css from the TS tokens so CSS consumers (apps/web) read the
// same canon as TS consumers (apps/ssh, packages/video). DESIGN.md stays the
// source of truth; index.ts mirrors it; this script mirrors index.ts into CSS.
// Run with: bun run --cwd packages/tokens generate

import { colors, radii } from "../src/index";

const toKebab = (value: string): string => value.replaceAll(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const lines: string[] = [
  "/* GENERATED by scripts/generate-css.ts from src/index.ts — do not edit by hand.",
  "   DESIGN.md is canonical; fix src/index.ts and re-run `bun run generate`. */",
  "",
  ":root {",
  ...Object.entries(colors).map(([name, value]) => `  --${toKebab(name)}: ${value};`),
  ...Object.entries(radii).map(([name, value]) => `  --rounded-${toKebab(name)}: ${value};`),
  "}",
  "",
];

await Bun.write(new URL("../src/tokens.css", import.meta.url), lines.join("\n"));
console.log("wrote src/tokens.css");
