import { describe, expect, test } from "bun:test";

import { colors, radii } from "../src/index";
import { renderTokensCss, TOKENS_CSS_URL } from "./generate-css";

// src/tokens.css IS A BUILD ARTIFACT THAT LIVES IN GIT.
//
// apps/web reads the CSS variables; apps/ssh and packages/video read the TS objects. The two
// are the same canon only for as long as somebody remembers to re-run `bun run generate` after
// touching src/index.ts — and forgetting leaves no trace: the app compiles, the types are
// right, and a colour is simply wrong on the web while being correct everywhere else. Nothing
// caught that, because this package had no tests and no `test` script for turbo to run.
//
// So the generator is re-run in memory and compared byte-for-byte with the committed file.
// The fix when this fails is one command: `bun run --cwd packages/tokens generate`.
//
// Deliberately NOT asserted here: any token VALUE. DESIGN.md is canonical for those; this
// only pins that the mirror is current.

describe("src/tokens.css is not stale", () => {
  test("matches a fresh render of the tokens, byte for byte", async () => {
    const committed = await Bun.file(TOKENS_CSS_URL).text();

    expect(committed).toBe(renderTokensCss());
  });

  test("carries every colour and radius token (the render covers both maps)", () => {
    const css = renderTokensCss();

    for (const name of Object.keys(colors)) {
      const variable = `--${name.replaceAll(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}:`;

      expect(css).toContain(variable);
    }

    for (const name of Object.keys(radii)) {
      expect(css).toContain(`--rounded-${name}:`);
    }
  });

  test("keeps the do-not-edit banner, so the file is never hand-maintained", () => {
    expect(renderTokensCss().startsWith("/* GENERATED by scripts/generate-css.ts")).toBe(true);
  });
});
