import { afterEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";

import {
  buildDumpSql,
  type DumpTable,
  type SchemaObject,
  type SqlValue,
} from "../../../../apps/web/src/lib/server/db-dump";

import {
  beginBackupOperation,
  type DumpSource,
  completeBackupOperation,
  createBackupRunCounters,
  failBackupOperation,
  hashFile,
  selectExpiredBackupKeys,
  signedPut,
  streamDumpSql,
  writeGzippedDump,
} from "./backup-sweep";

const HEADER = "-- Fluncle database backup. Generated by fluncle-backup at T. Do not edit by hand.";
const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    rmSync(directory, { force: true, recursive: true });
  }
});

async function rejectionMessage(promise: Promise<unknown>): Promise<string> {
  try {
    await promise;

    return "";
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
}

function fixtureSource(schema: SchemaObject[], tables: DumpTable[]): DumpSource {
  return {
    fetchPage: async (name, limit, offset) => {
      const table = tables.find((candidate) => candidate.name === name);

      if (!table) {
        return null;
      }

      return { columns: table.columns, rows: table.rows.slice(offset, offset + limit) };
    },
    fetchSchema: async () => schema,
    fetchSpot: async () => ({ count: 3, max: "zzz", min: "aaa" }),
  };
}

async function collect(
  source: DumpSource,
  options: { batchRows?: number } = {},
): Promise<{ manifest: Awaited<ReturnType<typeof streamDumpSql>>; sql: string }> {
  let sql = "";
  const manifest = await streamDumpSql(source, (chunk) => void (sql += chunk), {
    batchRows: options.batchRows,
    generatedAt: new Date("2026-07-26T02:00:00.000Z"),
    header: HEADER,
    sourceName: "fixture",
  });

  return { manifest, sql };
}

const SCHEMA: SchemaObject[] = [
  {
    name: "tracks",
    sql: "CREATE TABLE tracks (id TEXT, title TEXT, n INTEGER, embedding BLOB)",
    type: "table",
  },
  { name: "empty_table", sql: "CREATE TABLE empty_table (a TEXT)", type: "table" },
  {
    name: "tracks_title_idx",
    sql: "CREATE INDEX tracks_title_idx ON tracks (title)",
    type: "index",
  },
  { name: "tracks_view", sql: "CREATE VIEW tracks_view AS SELECT id FROM tracks", type: "view" },
];

const ROWS: SqlValue[][] = [
  ["a1", "Valley of the Shadow", 9007199254740993n, new Uint8Array([0, 15, 255])],
  ["b2", "Don't Stop 'til It's Over", 42, null],
  ["c3", null, 1.5, true],
];

const TABLES: DumpTable[] = [
  { columns: ["id", "title", "n", "embedding"], name: "tracks", rows: ROWS },
  { columns: ["a"], name: "empty_table", rows: [] },
];

describe("streamDumpSql — byte-for-byte the format the restore drill expects", () => {
  test("matches the repo's real buildDumpSql exactly", async () => {
    const { sql } = await collect(fixtureSource(SCHEMA, TABLES));

    expect(sql).toBe(buildDumpSql(SCHEMA, TABLES, HEADER));
  });

  test("the batch size never changes a byte", async () => {
    const reference = buildDumpSql(SCHEMA, TABLES, HEADER);

    for (const batchRows of [1, 2, 3, 500]) {
      const { sql } = await collect(fixtureSource(SCHEMA, TABLES), { batchRows });

      expect(sql).toBe(reference);
    }
  });

  test("a page that exactly fills the batch still terminates (no duplicate tail)", async () => {
    const { manifest, sql } = await collect(fixtureSource(SCHEMA, TABLES), { batchRows: 3 });

    expect(sql.split("INSERT INTO").length - 1).toBe(3);
    expect(manifest.tables.tracks).toBe(3);
  });

  test("the manifest keeps its shape: row counts, table count, byte count, spot check", async () => {
    const { manifest, sql } = await collect(fixtureSource(SCHEMA, TABLES));

    expect(manifest.tableCount).toBe(2);
    expect(manifest.tables).toEqual({ empty_table: 0, tracks: 3 });
    expect(manifest.sqlBytes).toBe(Buffer.byteLength(sql, "utf8"));
    expect(manifest.source).toBe("fixture");
    expect(manifest.generatedAt).toBe("2026-07-26T02:00:00.000Z");

    expect(manifest.spot).toEqual({
      column: "id",
      count: 3,
      max: "zzz",
      min: "aaa",
      table: "tracks",
    });
  });

  test("an unreadable table is skipped whole, exactly as before", async () => {
    const source = fixtureSource(SCHEMA, TABLES);
    const guarded: DumpSource = {
      ...source,
      fetchPage: async (name, limit, offset) =>
        name === "empty_table" ? null : source.fetchPage(name, limit, offset),
    };

    const { manifest } = await collect(guarded);

    expect(manifest.tableCount).toBe(1);
    expect(manifest.tables).toEqual({ tracks: 3 });
  });
});

describe("writeGzippedDump — the artifact on disk", () => {
  test("gunzips back to the same dump, and reports its size + hash", async () => {
    const dir = mkdtempSync(join(tmpdir(), "fluncle-dump-"));
    temporaryDirectories.push(dir);
    const path = join(dir, "fluncle.sql.gz");

    const { file, manifest } = await writeGzippedDump(fixtureSource(SCHEMA, TABLES), path, {
      generatedAt: new Date("2026-07-26T02:00:00.000Z"),
      header: HEADER,
      sourceName: "fixture",
    });

    expect(gunzipSync(readFileSync(path)).toString("utf8")).toBe(
      buildDumpSql(SCHEMA, TABLES, HEADER),
    );
    expect(file.bytes).toBe(statSync(path).size);
    expect(file.sha256).toBe(await hashFile(path));
    expect(manifest.sqlBytes).toBeGreaterThan(0);
  });
});

describe("the memory bound (the whole point of the rewrite)", () => {
  const ROW_COUNT = 200_000;
  const PAYLOAD = "x".repeat(950);
  const CEILING_BYTES = 192 * 1024 * 1024;

  test(`dumping ${ROW_COUNT} rows keeps peak RSS growth under ${CEILING_BYTES >> 20} MiB`, async () => {
    const schema: SchemaObject[] = [
      { name: "big", sql: "CREATE TABLE big (id INTEGER, payload TEXT)", type: "table" },
    ];

    const source: DumpSource = {
      fetchPage: async (_name, limit, offset) => {
        const rows: SqlValue[][] = [];

        for (let index = offset; index < Math.min(offset + limit, ROW_COUNT); index += 1) {
          rows.push([index, PAYLOAD]);
        }

        return { columns: ["id", "payload"], rows };
      },
      fetchSchema: async () => schema,
      fetchSpot: async () => ({ count: ROW_COUNT, max: ROW_COUNT - 1, min: 0 }),
    };

    const dir = mkdtempSync(join(tmpdir(), "fluncle-dump-big-"));
    temporaryDirectories.push(dir);
    const path = join(dir, "fluncle.sql.gz");

    Bun.gc(true);
    const baseline = process.memoryUsage.rss();
    let peak = baseline;

    const sample = () => {
      const rss = process.memoryUsage.rss();

      if (rss > peak) {
        peak = rss;
      }
    };
    const sampler = setInterval(sample, 25);

    let manifest;

    try {
      ({ manifest } = await writeGzippedDump(source, path, {
        generatedAt: new Date("2026-07-26T02:00:00.000Z"),
        header: HEADER,
        sourceName: "fixture",
      }));
    } finally {
      clearInterval(sampler);
      sample();
    }

    const growth = peak - baseline;

    console.log(
      `[memory bound] sqlBytes=${manifest.sqlBytes} gzipBytes=${statSync(path).size} ` +
        `rssBaseline=${baseline} rssPeak=${peak} growth=${growth}`,
    );

    expect(manifest.sqlBytes).toBeGreaterThan(190 * 1024 * 1024);
    expect(manifest.tables.big).toBe(ROW_COUNT);

    expect(growth).toBeLessThan(CEILING_BYTES);
  }, 180_000);
});

describe("signedPut — the artifact is uploaded without being held", () => {
  test("streams the file, signing a hash computed off disk", async () => {
    const dir = mkdtempSync(join(tmpdir(), "fluncle-put-"));
    temporaryDirectories.push(dir);
    const path = join(dir, "artifact.bin");
    const payload = Buffer.alloc(3 * 1024 * 1024, 7);

    await Bun.write(path, payload);

    const sha256 = await hashFile(path);
    let seen: { body: Buffer; headers: Record<string, string> } | null = null;

    const server = Bun.serve({
      fetch: async (request) => {
        seen = {
          body: Buffer.from(await request.arrayBuffer()),
          headers: Object.fromEntries(request.headers.entries()),
        };

        return new Response("", { status: 200 });
      },
      hostname: "127.0.0.1",
      port: 0,
    });

    try {
      await signedPut(`${server.url.origin}/fluncle-backups/db-backups/daily/2026-07-26/x.gz`, {
        accessKeyId: "test-access-key",
        body: { bytes: statSync(path).size, path, sha256 },
        contentType: "application/gzip",
        now: new Date("2026-07-26T02:00:00.000Z"),
        secretAccessKey: "test-secret-key",
      });
    } finally {
      await server.stop(true);
    }

    const received = seen as { body: Buffer; headers: Record<string, string> } | null;

    expect(received).not.toBeNull();
    expect(received?.body.equals(payload)).toBe(true);

    expect(received?.headers["x-amz-content-sha256"]).toBe(sha256);
    expect(received?.headers["content-length"]).toBe(String(payload.byteLength));
    expect(received?.headers.authorization).toContain(
      "Credential=test-access-key/20260726/auto/s3",
    );
    expect(received?.headers["content-type"]).toBe("application/gzip");
  });

  test("bytes in hand are signed the way the aws-sigv4 mirror always did", async () => {
    const body = new TextEncoder().encode('{"ok":true}\n');
    let seen: Record<string, string> = {};

    const server = Bun.serve({
      fetch: (request) => {
        seen = Object.fromEntries(request.headers.entries());

        return new Response("", { status: 200 });
      },
      hostname: "127.0.0.1",
      port: 0,
    });

    try {
      await signedPut(`${server.url.origin}/fluncle-backups/manifest.json`, {
        accessKeyId: "test-access-key",
        body,
        contentType: "application/json",
        now: new Date("2026-07-26T02:00:00.000Z"),
        secretAccessKey: "test-secret-key",
      });
    } finally {
      await server.stop(true);
    }

    const expected = createHash("sha256").update(body).digest("hex");

    expect(seen["x-amz-content-sha256"]).toBe(expected);
  });

  test("a non-2xx from R2 throws rather than reporting a backup that never landed", async () => {
    const server = Bun.serve({
      fetch: () => new Response("AccessDenied", { status: 403 }),
      hostname: "127.0.0.1",
      port: 0,
    });

    try {
      expect(
        await rejectionMessage(
          signedPut(`${server.url.origin}/fluncle-backups/x.gz`, {
            accessKeyId: "k",
            body: new Uint8Array([1]),
            contentType: "application/gzip",
            secretAccessKey: "s",
          }),
        ),
      ).toContain("failed (403)");
    } finally {
      await server.stop(true);
    }
  });
});

describe("selectExpiredBackupKeys — retention is unchanged", () => {
  test("keeps the newest N daily + N monthly folders and nothing else", () => {
    const keys = [
      "db-backups/daily/2026-07-24/fluncle.sql.gz",
      "db-backups/daily/2026-07-25/fluncle.sql.gz",
      "db-backups/daily/2026-07-26/fluncle.sql.gz",
      "db-backups/monthly/2026-06/fluncle.sql.gz",
      "db-backups/monthly/2026-07/fluncle.sql.gz",
      "db-backups/daily/not-a-date/fluncle.sql.gz",
    ];

    expect(
      selectExpiredBackupKeys(keys, {
        dailyPrefix: "db-backups/daily/",
        keepDaily: 2,
        keepMonthly: 1,
        monthlyPrefix: "db-backups/monthly/",
      }),
    ).toEqual([
      "db-backups/daily/2026-07-24/fluncle.sql.gz",
      "db-backups/monthly/2026-06/fluncle.sql.gz",
    ]);
  });

  test("the box-state leg reuses it over its own prefixes", () => {
    const keys = [
      "box-state/daily/2026-07-25/box-state.tar.gz.enc",
      "box-state/daily/2026-07-26/box-state.tar.gz.enc",
      "box-state/monthly/2026-07/box-state.tar.gz.enc",
    ];

    expect(
      selectExpiredBackupKeys(keys, {
        dailyPrefix: "box-state/daily/",
        keepDaily: 1,
        keepMonthly: 6,
        monthlyPrefix: "box-state/monthly/",
      }),
    ).toEqual(["box-state/daily/2026-07-25/box-state.tar.gz.enc"]);
  });
});

describe("run-ledger summary counters", () => {
  test("counts attempted backup operations without promoting a leg failure to run errors", () => {
    const counters = createBackupRunCounters();

    beginBackupOperation(counters);
    completeBackupOperation(counters);
    beginBackupOperation(counters);
    failBackupOperation(counters);

    expect(counters).toEqual({ checked: 2, errors: 0, failed: 1, produced: 1 });

    expect("queueDepth" in counters).toBe(false);
    expect("queue_depth" in counters).toBe(false);
    expect("expectedIntervalMs" in counters).toBe(false);
    expect("expected_interval_ms" in counters).toBe(false);
  });

  test("a preflight failure reports a failed run with zero attempted operations", () => {
    const result = spawnSync(
      process.execPath,
      [
        join(import.meta.dir, "backup-sweep.ts"),
        "--out",
        "/tmp/fluncle-backup-summary-db",
        "--box-state-out",
        "/tmp/fluncle-backup-summary-box",
      ],
      { encoding: "utf8" },
    );
    const summary = JSON.parse(result.stdout.trim()) as Record<string, unknown>;

    expect(result.status).toBe(1);
    expect(summary).toMatchObject({ checked: 0, errors: 1, failed: 0, produced: 0 });
  });
});
