export const VECTOR_FALLBACK_DEADLINE_MS = 12_000;

const VECTOR_ENDPOINT_PROBE_MARGIN_MS = 5_000;

export const VECTOR_ENDPOINT_PROBE_TIMEOUT_MS =
  VECTOR_FALLBACK_DEADLINE_MS + VECTOR_ENDPOINT_PROBE_MARGIN_MS;

export const MIX_RAIL_SCAN_DEADLINE_MS = 6_000;

export const MIX_RAIL_DEADLINE_MS = 8_000;
